item { 
	name:'rat'
	id:1
}
item { 
	name:'ox'
	id:2
}
item { 
	name:'tiger'
	id:3
}
item { 
	name:'hare'
	id:4
}
item { 
	name:'dragon'
	id:5
}
item { 
	name:'snake'
	id:6
}
item { 
	name:'horse'
	id:7
}
item { 
	name:'ram'
	id:8
}
item { 
	name:'monkey'
	id:9
}
item { 
	name:'bird'
	id:10
}
item { 
	name:'dog'
	id:11
}
item { 
	name:'boar'
	id:12
}
